### ISSUE TITLE
求帮助

### ISSUE THREAD

**Issue by Zlztai** [zixiiu/Digital_Life_Server#11]
报错如下：
###################################
D:\work\DL_Server>run-gpt3.5-api.bat
2023-05-10 09:42:22,514 INFO Initializing Server...
2023-05-10 09:42:22,514 INFO Initializing ASR Service...
2023-05-10 09:42:28,098 INFO Initializing ChatGPT Service...
2023-05-10 09:42:28,098 INFO chatGPT prompt: paimon35.txt
2023-05-10 09:42:28,519 INFO machine identifier: EE:47:73:19:3B:64
2023-05-10 09:42:28,731 INFO using custom API proxy, with rate limit.
2023-05-10 09:42:29,114 INFO API Chatbot initialized.
2023-05-10 09:42:29,114 INFO Initializing TTS Service for character_paimon...
2023-05-10 09:42:29,940 ERROR
2023-05-10 09:42:29,945 ERROR Traceback (most recent call last):
  File "D:\work\DL_Server\SocketServer.py", line 196, in <module>
    s = Server(args)
  File "D:\work\DL_Server\SocketServer.py", line 86, in __init__
    self.tts = TTService.TTService(*self.char_name[args.character])
  File "D:\work\DL_Server\TTS\TTService.py", line 42, in __init__
    _ = utils.load_checkpoint(model, self.net_g, None)
  File "D:\work\DL_Server\TTS\vits\utils.py", line 20, in load_checkpoint
    assert os.path.isfile(checkpoint_path)
AssertionError
####################################################

**Comment by zixiiu** [comment]
应该是模型没有放对地方。检查一下 TTS/models/paimon6k_390k.pth 这个文件是否存在

**Comment by Zlztai** [comment]
位置好像没问题
![屏幕截图 2023-05-10 125157](https://github.com/zixiiu/Digital_Life_Server/assets/121115645/604f5828-81ec-4193-bef8-2f14fe5126e7)

**Comment by Zlztai** [comment]
好吧，模型的名字必须为 “paimon6k_390k.pth”  ，否则识别不出来；我用的之前的paimon模型名字。
