### ISSUE TITLE
TTService在处理GPT返回的数据时，如果存在颜文字或其他特殊字符会导致程序中断

### ISSUE THREAD

**Issue by pokebox** [zixiiu/Digital_Life_Server#19]
在函数`self.chat_gpt.ask_stream(ask_text)`获取到gpt的数据后，如果返回的数据中包含类似``颜文字等特殊字符时，传递给TTS发音会导致报错：

`GPTService.py[line:96] INFO: ChatGPT Stream Response: 请欣赏！♪♪(๑•̀ㅂ•́)و✧♪♪, @Time 4.34`

```
ERROR: 输入的数据不在转化范围内：๑！
ERROR: Traceback (most recent call last):
  File "c:\Users\Digital_Life_Server\test.py", line 130, in listen
    self.send_voice(sentence)
  File "c:\Users\Digital_Life_Server\test.py", line 177, in send_voice
    self.tts.read_save(resp_text, self.tmp_proc_file, self.tts.hps.data.sampling_rate)
  File "c:\Users\Digital_Life_Server\TTS\TTService.py", line 55, in read_save
    au = self.read(text)
  File "c:\Users\Digital_Life_Server\TTS\TTService.py", line 45, in read
    stn_tst = get_text(text, self.hps)
  File "c:\Users\Digital_Life_Server\TTS\TTService.py", line 24, in get_text
    text_norm = text_to_sequence(text, hps.data.text_cleaners)
  File "c:\Users\Digital_Life_Server\TTS\vits\text\__init__.py", line 21, in text_to_sequence
    clean_text = _clean_text(text, cleaner_names)
  File "c:\Users\Digital_Life_Server\TTS\vits\text\__init__.py", line 55, in _clean_text
    text = cleaner(text)
  File "C:\Users\Digital_Life_Server\TTS/vits\text\cleaners.py", line 34, in chinese_cleaners
    text = number_to_chinese(text)
  File "C:\Users\Digital_Life_Server\TTS/vits\text\mandarin.py", line 239, in number_to_chinese
    text = text.replace(number, cn2an.an2cn(number), 1)
  File "C:\Users\Digital_Life_Server\.venv\lib\site-packages\cn2an\an2cn.py", line 40, in an2cn
    self.__check_inputs_is_valid(inputs)
  File "C:\Users\Digital_Life_Server\.venv\lib\site-packages\cn2an\an2cn.py", line 139, in __check_inputs_is_valid
    raise ValueError(f"输入的数据不在转化范围内：{data}！")
ValueError: 输入的数据不在转化范围内：๑！```

**Comment by folbird** [comment]
哥们搞到第几步了，要不要加个联系方式交流一下

**Comment by tdou-guo** [comment]
请问下 这个TTService 的 vits怎么训练其他语言模型哈，
我用https://github.com/Plachtaa/VITS-fast-fine-tuning 训练出来的模型 无法使用，模型不匹配 这个用那个仓库去训练的tts 的vits模型哈
我的微信vvvgjm

**Comment by wzyRuler** [comment]
请问我的运行run-gpt3.5-api.bat过后会报错显示
ImportError: cannot import name 'TTService' from 'TTS' 
但是我看了是安装了tts的这是怎么回事？
