### ISSUE TITLE
在回复语音完成之后报错（ PySoundFile failed. Trying audioread instead.）

### ISSUE THREAD

**Issue by mrtank2333** [zixiiu/Digital_Life_Server#30]
**语音已经正确在客户端播放，出错是在对话了几轮之后才出的**

2023-05-17 19:38:34,106 INFO VITS Synth Done, time used 0.56
2023-05-17 19:38:34,172 INFO Sentiment Engine Infer: 0
2023-05-17 19:38:34,681 INFO WAV SENT, size 2487855
2023-05-17 19:39:14,895 INFO WAV file received and saved.
2023-05-17 19:39:15,100 INFO ASR Result: ['呃我有胡桃叶兰钟梨还有万叶然后还']. time used 0.19.
2023-05-17 19:39:42,389 INFO ChatGPT Response: 好的，根据你提供的信息，我可以给你一些深渊配对建议。首先，你可以选择胡桃
和叶兰作为主DPS，因为他们都有比较高的输出能力和优秀的技能效果。其次，你可以选择钟、梨或者万叶作为辅助DPS或支援角色，他们都有自己的特点和优势，可以为队伍提供额外的输出或支援能力。最后，你需要根据深渊的要求和敌人的属性来选择合适的角色，比如选择具有火属性或雷属性的角色来对付水属性或冰属性的敌人。总的来说，你的队伍已经比较平衡了，只需要根据具体情况做出一些微调就可以了。, time used 27.29
2023-05-17 19:39:43,136 INFO VITS Synth Done, time used 0.74
2023-05-17 19:39:43,220 INFO Sentiment Engine Infer: 0
2023-05-17 19:39:43,733 INFO WAV SENT, size 3402799
2023-05-17 19:39:44,238 INFO WAV file received and saved.
H:\AITakagi_Digital_Life\Digital_Life_Server\SocketServer.py:184: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(self.tmp_recv_file, sr=None, mono=False)
H:\AITakagi_Digital_Life\Digital_Life_Server\venv\lib\site-packages\librosa\core\audio.py:184:FutureWarning:librosa.core.audio.__audioread_load
        Deprecated as of librosa version 0.10.0.
        It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
2023-05-17 19:39:44,674 ERROR
2023-05-17 19:39:44,705 ERROR Traceback (most recent call last):
  File "H:\AITakagi_Digital_Life\Digital_Life_Server\venv\lib\site-packages\librosa\core\audio.py", line 176, in load
    y, sr_native = __soundfile_load(path, offset, duration, dtype)
  File "H:\AITakagi_Digital_Life\Digital_Life_Server\venv\lib\site-packages\librosa\core\audio.py", line 209, in __soundfile_load
    context = sf.SoundFile(path)
  File "H:\AITakagi_Digital_Life\Digital_Life_Server\venv\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "H:\AITakagi_Digital_Life\Digital_Life_Server\venv\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'tmp/server_received.wav': Format not recognised.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\AITakagi_Digital_Life\Digital_Life_Server\SocketServer.py", line 106, in listen
    ask_text = self.process_voice()
  File "H:\AITakagi_Digital_Life\Digital_Life_Server\SocketServer.py", line 184, in process_voice
    y, sr = librosa.load(self.tmp_recv_file, sr=None, mono=False)
  File "H:\AITakagi_Digital_Life\Digital_Life_Server\venv\lib\site-packages\librosa\core\audio.py", line 184, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "H:\AITakagi_Digital_Life\Digital_Life_Server\venv\lib\site-packages\decorator.py", line 232, in fun return caller(func, *(extras + args), **kw)
  File "H:\AITakagi_Digital_Life\Digital_Life_Server\venv\lib\site-packages\librosa\util\decorators.py", line 60, in __wrapper
    return func(*args, **kwargs)
  File "H:\AITakagi_Digital_Life\Digital_Life_Server\venv\lib\site-packages\librosa\core\audio.py", line 241, in __audioread_load
    reader = audioread.audio_open(path)
  File "H:\AITakagi_Digital_Life\Digital_Life_Server\venv\lib\site-packages\audioread\__init__.py", line 132, in audio_open
    raise NoBackendError()
audioread.exceptions.NoBackendError

**Comment by kxylxx** [comment]
请教一下，您是不是对SocketServer.py文件做了修改，能分享给我看一下吗？

**Comment by mrtank2333** [comment]
> 请教一下，您是不是对SocketServer.py文件做了修改，能分享给我看一下吗？

我没改这个文件

**Comment by kxylxx** [comment]
直接就跑通了吗？

**Comment by mrtank2333** [comment]
> 直接就跑通了吗？

肯定不啊，缺config文件的，要在b站极客湾分享的那个发布版里面拷贝到根目录\config文件夹里，有两个文件要拷贝，一个config.ini，一个model.ini，我当时还遇到环境问题，一点一点补全库才跑起来的（现在又炸了），另外我用的python版本是python10.0。以及你还得在正式版文件夹里面拷贝SocketServer\monotonic_align\monotonic_align\core.cp310-win_amd64.pyd到Digital_Life_Server\TTS\vits\monotonic_align\monotonic_align里面或者Digital_Life_Server\TTS\vits\monotonic_align\里面

**Comment by kxylxx** [comment]
好的感谢，我来试一下，我现在用的3.9.16，开始用3.10有些包装不上，就换了3.9
