### ISSUE TITLE
这个问题出在哪啊

### ISSUE THREAD

**Issue by wfxiaoyun** [zixiiu/Digital_Life_Server#34]
2023-05-19 11:49:30,905 INFO Server is listening on 192.168.8.140:38438...
2023-05-19 11:50:10,612 INFO Initializing Server...
2023-05-19 11:50:10,620 INFO Initializing ASR Service...
2023-05-19 11:50:15,608 INFO Initializing ChatGPT Service...
2023-05-19 11:50:15,610 INFO chatGPT prompt: yunfei35.txt
2023-05-19 11:50:16,162 INFO machine identifier: 7C:50:79:EA:1A:7D
2023-05-19 11:50:16,341 INFO using custom API proxy, with rate limit.
2023-05-19 11:50:16,754 INFO API Chatbot initialized.
2023-05-19 11:50:16,755 INFO Initializing TTS Service for character_yunfei...
2023-05-19 11:50:19,489 INFO Loaded checkpoint 'TTS/models/yunfeimix2_53k.pth' (iteration 1893)
2023-05-19 11:50:19,527 INFO Initializing Sentiment Engine...
2023-05-19 11:50:21,050 INFO Server is listening on 192.168.8.140:38438...
2023-05-19 11:50:48,498 INFO Connected by ('192.168.8.88', 33104)
2023-05-19 11:51:04,357 INFO WAV file received and saved.
2023-05-19 11:51:05,626 INFO ASR Result: ['你好你好收到收到请回答收到请回答']. time used 0.29.
2023-05-19 11:51:06,845 ERROR Expecting value: line 1 column 1 (char 0)
2023-05-19 11:51:06,847 ERROR Traceback (most recent call last):
  File "SocketServer.py", line 107, in listen
  File "GPT\GPTService.py", line 82, in ask_stream
  File "revChatGPT\V3.py", line 215, in ask_stream
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2023-05-19 11:51:06,847 INFO Server is listening on 192.168.8.140:38438...

**Comment by danaoshuiping** [comment]
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 一摸一样的问题，同求答

**Comment by Raysquare** [comment]
revChatGPT库里面发生了错误，具体怎么导致文本解码错误不太清楚。工程里面的revChatGPT版本是5.0，我试着将它更新到最新版本6.1.2解决了问题，大家可以试试。
