### ISSUE TITLE
这个问题怎么解决呀

### ISSUE THREAD

**Issue by faithererer** [zixiiu/Digital_Life_Server#38]
```python
2023-05-23 12:34:38,359 INFO Initializing Server...
2023-05-23 12:34:38,360 INFO Initializing ASR Service...
2023-05-23 12:34:41,597 INFO Initializing ChatGPT Service...
2023-05-23 12:34:41,598 INFO chatGPT prompt: paimon35.txt
2023-05-23 12:34:41,803 INFO machine identifier: 14:5A:FC:23:CD:47
2023-05-23 12:34:42,041 INFO using custom API proxy, with rate limit.
2023-05-23 12:34:42,315 INFO API Chatbot initialized.
2023-05-23 12:34:42,316 INFO Initializing TTS Service for character_paimon...
2023-05-23 12:34:43,186 INFO Loaded checkpoint 'TTS/models/paimon6k_390k.pth' (iteration 8864)
2023-05-23 12:34:43,218 INFO Initializing Sentiment Engine...
2023-05-23 12:34:43,802 ERROR HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-chinese/resolve/main/vocab.txt (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
2023-05-23 12:34:43,809 ERROR Traceback (most recent call last):
  File "F:\WorkSpace\python\paimeng\Digital_Life_Server\venv\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "F:\WorkSpace\python\paimeng\Digital_Life_Server\venv\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "F:\WorkSpace\python\paimeng\Digital_Life_Server\venv\lib\site-packages\urllib3\connection.py", line 364, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "F:\WorkSpace\python\paimeng\Digital_Life_Server\venv\lib\site-packages\urllib3\connection.py", line 499, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "F:\WorkSpace\python\paimeng\Digital_Life_Server\venv\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "F:\WorkSpace\python\paimeng\Digital_Life_Server\venv\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "E:\python\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\python\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "E:\python\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

```

**Comment by zixiiu** [comment]
可能需要准备一下梯子
