### ISSUE TITLE
ModuleNotFoundError: No module named 'monotonic_align.monotonic_align.core'

### ISSUE THREAD

**Issue by GreatWildFire** [zixiiu/Digital_Life_Server#4]
cmd.exe /c run-gpt3.5-api.bat 
Traceback (most recent call last):   File "E:\Digital Human\Digital_Life_Server\SocketServer.py", line 18, in <module>     from TTS import TTService   File "E:\Digital Human\Digital_Life_Server\TTS\TTService.py", line 14, in <module>     from TTS.vits.models import SynthesizerTrn   File "E:\Digital Human\Digital_Life_Server\TTS\vits\models.py", line 10, in <module>     import monotonic_align   File "E:\Digital Human\Digital_Life_Server\TTS/vits\monotonic_align\__init__.py", line 3, in <module>     from .monotonic_align.core import maximum_path_c 
ModuleNotFoundError: No module named 'monotonic_align.monotonic_align.core'

已经把core.cp38-win_amd64.pyd文件放在\TTS\vits\monotonic_align\monotonic_align文件夹下了，依然报错

**Comment by zixiiu** [comment]
这个文件放在\TTS\vits\monotonic_align 里

**Comment by Lion-ly** [comment]
core.cp38-win_amd64.pyd文件 在哪里获取的啊？
