### ISSUE TITLE
按说明配置完成后，启动时说没有pytorch。但是运行python里可以找到，请问怎么解决这个问题？

### ISSUE THREAD

**Issue by AnJiaqi0926** [zixiiu/Digital_Life_Server#47]
![image](https://github.com/zixiiu/Digital_Life_Server/assets/111276326/08455745-f61f-43cd-a832-a01f1960f368)

(base) D:\Digital_Life_Server>run-gpt3.5-api.bat
D:\Digital_Life_Server\venv\lib\site-packages\revChatGPT\__init__.py:27: UserWarning: The current Python is not a recommended version, 3.10+ is recommended
  __import__("warnings").warn(
Traceback (most recent call last):
  File "D:\Digital_Life_Server\SocketServer.py", line 18, in <module>
    from TTS import TTService
  File "D:\Digital_Life_Server\TTS\TTService.py", line 9, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

(base) D:\Digital_Life_Server>python
Python 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>>

**Comment by DancingLeaf123** [comment]
我估计改一下bat里面的 工作目录
开头加这行
CD %~dp0

**Comment by AnJiaqi0926** [comment]
好像没解决问题？尝试了一下不行？

**Comment by wayne78ck6** [comment]
看run-gpt3.5-api.bat裡面是.\venv\Scripts\python.exe，應該是建了一個venv環境了。
如果沒出錯的話，應該是跑過readme_detail.md裡面的建置過程？
下面那個(base) D:\Digital_Life_Server>python 改成用 .\venv\Scripts\python.exe 確認看看裡面有沒有torch好了，有可能你的pytorch是裝在外面但是venv沒裝。

如果是按照主頁的方式，看起來是套件裝在base環境不再venv裡面，
試試看把run-gpt3.5-api.bat裡面的.\venv\Scripts\python.exe 改成python，說不定就能跑了。

**Comment by wzyRuler** [comment]
应该是pytorch库和其他库的版本有点冲突
如果是虚拟环境的问题的话是显示 找不到指定系统文件
你的虚拟环境没有创建在当前文件夹下的话把run-gpt3.5-api.bat文件里面最下面那行的%SCRIPT_NAME%前面的路径改成你创建的conda环境的python.exe的绝对路径就行了
