### ISSUE TITLE
网络结构好像不匹配

### ISSUE THREAD

**Issue by Colwzq** [zixiiu/Digital_Life_Server#5]
```
2023-05-08 20:53:08,741 INFO Initializing Server...
2023-05-08 20:53:08,744 INFO Initializing ASR Service...
2023-05-08 20:53:11,130 INFO Initializing ChatGPT Service...
2023-05-08 20:53:11,131 INFO chatGPT prompt: paimon35.txt
2023-05-08 20:53:11,201 INFO machine identifier: 50:EB:F6:ED:94:FE
2023-05-08 20:53:11,299 INFO using custom API proxy, with rate limit.
2023-05-08 20:53:11,485 INFO API Chatbot initialized.
2023-05-08 20:53:11,485 INFO Initializing TTS Service for character_paimon...
2023-05-08 20:53:12,166 ERROR Error(s) in loading state_dict for SynthesizerTrn:
        size mismatch for enc_p.emb.weight: copying a param with shape torch.Size([52, 192]) from checkpoint, the shape in current model is torch.Size([178, 192]).
2023-05-08 20:53:12,168 ERROR Traceback (most recent call last):
  File "h:\Digital_Life_Server-master\SocketServer.py", line 196, in <module>
    s = Server(args)
  File "h:\Digital_Life_Server-master\SocketServer.py", line 86, in __init__
    self.tts = TTService.TTService(*self.char_name[args.character])
  File "h:\Digital_Life_Server-master\TTS\TTService.py", line 42, in __init__
    _ = utils.load_checkpoint(model, self.net_g, None)
  File "h:\Digital_Life_Server-master\TTS\vits\utils.py", line 40, in load_checkpoint
    model.load_state_dict(new_state_dict)
  File "C:\Users\colwzq\anaconda3\envs\digital-life\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrn:
        size mismatch for enc_p.emb.weight: copying a param with shape torch.Size([52, 192]) from checkpoint, the shape in current model is torch.Size([178, 192]).
```
yunfei和paimon都试过了，报错一致

**Comment by Colwzq** [comment]
solved

**Comment by yjjjj** [comment]
@Colwzq 我也是一样的报错，怎么解决的呀。。。

**Comment by stanle1** [comment]
最后怎么解决？

**Comment by stanle1** [comment]
没事了 发现是 [symbols.py] 的长度 和真实json里的长度不一致做成 已解决

**Comment by Fatfish588** [comment]
> 没事了 发现是 [symbols.py] 的长度 和真实json里的长度不一致做成 已解决

我正在尝试使用这个模型，但是这个模型在其他的框架或者GUI里也出现了这个问题，我想知道具体不一致的地方在哪里，可以教教我怎么修改他吗？
