### ISSUE TITLE
配置应该是成功了，但是启动run.bat后显示下面这样，该怎么做？

### ISSUE THREAD

**Issue by AnJiaqi0926** [zixiiu/Digital_Life_Server#51]
![image](https://github.com/zixiiu/Digital_Life_Server/assets/111276326/9d489e5c-3677-43ad-bc38-d31487508929)

2023-05-31 20:47:40,831 ERROR [WinError 10053] 你的主机中的软件中止了一个已
建立的连接。
2023-05-31 20:47:40,832 ERROR Traceback (most recent call last):
  File "D:\Digital_Life_Server\SocketServer.py", line 101, in listen
    file = self.__receive_file()
  File "D:\Digital_Life_Server\SocketServer.py", line 157, in __receive_file
    data = self.conn.recv(1024)
ConnectionAbortedError: [WinError 10053] 你的主机中的软件中止了一个已建立的 连接。

2023-05-31 20:47:40,834 INFO Server is listening on 192.168.206.1:38438...
2023-05-31 20:47:40,835 INFO Connected by ('192.168.206.1', 51163)

切换了vpn后，显示connected了，但是仍然没法打开？

**Comment by a1309256** [comment]
same error

**Comment by nanayashiki1215** [comment]
同样错误 插眼

**Comment by wlwwew** [comment]
有没有大佬解决了这问题的，有偿
