### ISSUE TITLE
纯小白，启动不了

### ISSUE THREAD

**Issue by XCCreeper** [zixiiu/Digital_Life_Server#59]
这是要魔法上网·吗？如果是代理咋填？
电脑上还装过Stable Diffusion

 
2023-06-07 12:31:42,336 INFO Initializing Server...
2023-06-07 12:31:42,340 INFO Initializing ASR Service...
2023-06-07 12:31:45,108 INFO Initializing ChatGPT Service...
2023-06-07 12:31:45,109 INFO chatGPT prompt: paimon35.txt
2023-06-07 12:31:45,200 INFO machine identifier: 64:6E:E0:99:76:D6
2023-06-07 12:31:45,288 INFO using custom API proxy, with rate limit.
2023-06-07 12:31:45,506 INFO API Chatbot initialized.
2023-06-07 12:31:45,506 INFO Initializing TTS Service for character_paimon...
2023-06-07 12:31:46,235 INFO Loaded checkpoint 'TTS/models/paimon6k_390000.pth' (iteration 8864)
2023-06-07 12:31:46,266 INFO Initializing Sentiment Engine...
2023-06-07 12:31:49,735 ERROR Can't load tokenizer for 'bert-base-chinese'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'bert-base-chinese' is the correct path to a directory containing all relevant files for a BertTokenizer tokenizer.
2023-06-07 12:31:49,736 ERROR Traceback (most recent call last):
  File "SocketServer.py", line 195, in <module>
  File "SocketServer.py", line 88, in __init__
  File "SentimentEngine\SentimentEngine.py", line 21, in __init__
  File "transformers\tokenization_utils_base.py", line 1788, in from_pretrained
OSError: Can't load tokenizer for 'bert-base-chinese'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'bert-base-chinese' is the correct path to a directory containing all relevant files for a BertTokenizer tokenizer.

服务器进程已退出！

**Comment by lichenyigit** [comment]
需要科学上网，从hf上下载模型
