### ISSUE TITLE
是不是漏提交了 ‘TTS/models/catmix.json’，运行时候提示没有该文件

### ISSUE THREAD

**Issue by sfy2371** [zixiiu/Digital_Life_Server#73]
>run-gpt3.5-api.bat
E:\artificalntelligent\Digital_Life_Server\venv\lib\site-packages\revChatGPT\__init__.py:27: UserWarning: The current Python is not a recommended version, 3.10+ is recommended
  __import__("warnings").warn(
2023-07-06 14:15:20,810 INFO Initializing Server...
2023-07-06 14:15:20,815 INFO Initializing ASR Service...
2023-07-06 14:15:23,847 INFO Initializing ChatGPT Service...
2023-07-06 14:15:23,848 INFO chatGPT prompt: catmaid35.txt
2023-07-06 14:15:24,057 INFO machine identifier: 18:C0:4D:E6:EA:6D
2023-07-06 14:15:24,192 INFO using custom API proxy, with rate limit.
2023-07-06 14:15:24,436 INFO API Chatbot initialized.
2023-07-06 14:15:24,436 INFO Initializing TTS Service for character_catmaid...
2023-07-06 14:15:24,437 ERROR [Errno 2] No such file or directory: 'TTS/models/catmix.json'
2023-07-06 14:15:24,438 ERROR Traceback (most recent call last):
  File "E:\artificalntelligent\Digital_Life_Server\SocketServer.py", line 198, in <module>
    s = Server(args)
  File "E:\artificalntelligent\Digital_Life_Server\SocketServer.py", line 88, in __init__
    self.tts = TTService.TTService(*self.char_name[args.character])
  File "E:\artificalntelligent\Digital_Life_Server\TTS\TTService.py", line 34, in __init__
    self.hps = utils.get_hparams_from_file(cfg)
  File "E:\artificalntelligent\Digital_Life_Server\TTS\vits\utils.py", line 186, in get_hparams_from_file
    with open(config_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'TTS/models/catmix.json'

Traceback (most recent call last):
  File "E:\artificalntelligent\Digital_Life_Server\SocketServer.py", line 203, in <module>
    raise e
  File "E:\artificalntelligent\Digital_Life_Server\SocketServer.py", line 198, in <module>
    s = Server(args)
  File "E:\artificalntelligent\Digital_Life_Server\SocketServer.py", line 88, in __init__
    self.tts = TTService.TTService(*self.char_name[args.character])
  File "E:\artificalntelligent\Digital_Life_Server\TTS\TTService.py", line 34, in __init__
    self.hps = utils.get_hparams_from_file(cfg)
  File "E:\artificalntelligent\Digital_Life_Server\TTS\vits\utils.py", line 186, in get_hparams_from_file
    with open(config_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'TTS/models/catmix.json'

**Comment by sfy2371** [comment]
删除猫粮语音包就好

**Comment by lwc6666** [comment]
你好 我也遇到了同样的问题 
请是从哪里删除语音包呢

**Comment by sfy2371** [comment]
> 

根目录下SocketService.py 的78行还是88行来着删除，run.gpt-3.4..bat里换其他模型。
