### ISSUE TITLE
有大佬知道卡在语音识别文字这一步没反应怎么办吗

### ISSUE THREAD

**Issue by Slldyd2077** [zixiiu/Digital_Life_Server#75]
![image](https://github.com/zixiiu/Digital_Life_Server/assets/129566176/e3d6fe46-0b70-473c-8329-356fa6446ac8)
按z后一直2023-07-10 08:46:36,451 INFO Server is listening on 192.168.0.116:38438...
2023-07-10 08:47:06,684 INFO Connected by ('192.168.0.116', 2094)
然后就没动静了

**Comment by sfy2371** [comment]
服务端根目录的tmp文件夹建了么

**Comment by Slldyd2077** [comment]
> 服务端根目录的tmp文件夹建了么

qaq 一直都有，刚在里面还翻出来了某一次接收和答复的音频文件，但是再测试文件夹里就没有任何文件生成了了

**Comment by sfy2371** [comment]
你前端展示是自己弄的么，还是直接用他们打包好的客户端

**Comment by Slldyd2077** [comment]
> 你前端展示是自己弄的么，还是直接用他们打包好的客户端

两种方法都试了，同样的问题

**Comment by sfy2371** [comment]
哦哦，自己直接启的前端项目比较慢，我当时以为也有问题，但是后来多等了一会就好了

**Comment by lhcpeter** [comment]
> 

这种怎么建，老哥？
2023-07-27 10:52:01,792 INFO Initializing Sentiment Engine...
2023-07-27 10:52:02,822 INFO Server is listening on 192.168.0.100:38438...
2023-07-27 10:52:29,674 INFO Connected by ('192.168.0.100', 5298)
2023-07-27 10:52:35,183 ERROR [Errno 2] No such file or directory: 'tmp/server_received.wav'
2023-07-27 10:52:35,184 ERROR Traceback (most recent call last):
  File "SocketServer.py", line 105, in listen
    with open(self.tmp_recv_file, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/server_received.wav'

**Comment by lhcpeter** [comment]
> 服务端根目录的tmp文件夹建了么

这种情况怎么建，老哥？
2023-07-27 10:52:01,792 INFO Initializing Sentiment Engine...
2023-07-27 10:52:02,822 INFO Server is listening on 192.168.0.100:38438...
2023-07-27 10:52:29,674 INFO Connected by ('192.168.0.100', 5298)
2023-07-27 10:52:35,183 ERROR [Errno 2] No such file or directory: 'tmp/server_received.wav'
2023-07-27 10:52:35,184 ERROR Traceback (most recent call last):
File "SocketServer.py", line 105, in listen
with open(self.tmp_recv_file, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/server_received.wav'
