### ISSUE TITLE
使用VITS-fast-fine-tuning项目训练了自己的模型，放入项目运行下面报错。

### ISSUE THREAD

**Issue by WellTung666** [zixiiu/Digital_Life_Server#78]
使用[VITS-fast-fine-tuning](https://github.com/Plachtaa/VITS-fast-fine-tuning)项目训练了自己的模型，放入项目运行下面报错，请问要怎么解决呢？ 谢谢~

```
2023-07-25 16:13:49,858 ERROR Traceback (most recent call last):
  File "E:\work\Digital_Life_Server\SocketServer.py", line 199, in <module>
    s = Server(args)
        ^^^^^^^^^^^^
  File "E:\work\Digital_Life_Server\SocketServer.py", line 89, in __init__
    self.tts = TTService.TTService(*self.char_name[args.character])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\work\Digital_Life_Server\TTS\TTService.py", line 42, in __init__
    _ = utils.load_checkpoint(model, self.net_g, None)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\work\Digital_Life_Server\TTS\vits\utils.py", line 40, in load_checkpoint
    model.load_state_dict(new_state_dict)
  File "D:\Program\Anaconda3\envs\life\Lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrn:
        size mismatch for enc_p.emb.weight: copying a param with shape torch.Size([50, 192]) from checkpoint, the shape in current model is torch.Size([52, 192]).

Traceback (most recent call last):
  File "E:\work\Digital_Life_Server\SocketServer.py", line 204, in <module>
    raise e
  File "E:\work\Digital_Life_Server\SocketServer.py", line 199, in <module>
    s = Server(args)
        ^^^^^^^^^^^^
  File "E:\work\Digital_Life_Server\SocketServer.py", line 89, in __init__
    self.tts = TTService.TTService(*self.char_name[args.character])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\work\Digital_Life_Server\TTS\TTService.py", line 42, in __init__
    _ = utils.load_checkpoint(model, self.net_g, None)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\work\Digital_Life_Server\TTS\vits\utils.py", line 40, in load_checkpoint
    model.load_state_dict(new_state_dict)
  File "D:\Program\Anaconda3\envs\life\Lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    rai
```

**Comment by WellTung666** [comment]
已解决~
